
---

- name: Install packages 
  package:
        name: "{{ packages }}"
  vars:
     packages:
     - epel-release 
     - strace
     - procps-ng 
     - traceroute
     - tcpdump
     - util-linux 
     - lsof 
     - dstat 
     - oprofile 
     - valgrind 
     - kdesdk-kcachegrind 
     - binutils 
     - nmap
     - sysstat
     - net-tools
     - iproute
     - ltrace
     - iptraf
     - ethtool
     - iotop
     - blktrace
     - perf
     - coreutils
     - hdparm
     - fio
     - httpd-tools 
     - openssl
     - iputils
     - hping3
     - iperf
     - mtr
     - python
     - python-devel
     - python-pip
     - byacc 
     - flex 
     - ncurses 
     - ncurses-devel 

- name: Install pip with upgrade 
  pip: 
     name: pip  
     extra_args: --upgrade
  

- name: Install pip packages
  pip:
    name: "{{ packages }}"
  vars:
    packages:
    - pgen 
    - memprof 



- name: Install tiptop
  command: bash "{{ role_path }}/files/tiptop.sh"
  tags: tiptop

- name: Install rdmsr 
  command: bash "{{ role_path }}/files/rdmsr.sh"
  tags: rdmsr

- name: Install pcstat 
  command: bash "{{ role_path }}/files/pcstat.sh"
  tags: pcstat 
